server:
  port: 22260
spring:
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: 222222
    connection-timeout: 1s
    socket-timeout: 15s
  ai:
    vectorstore:
      elasticsearch:
        initialize-schema: true
        dimensions: 768
        index-name: vector-index2
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.2:latest
      embedding:
        model: nomic-embed-text:v1.5
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
