spring:
  elasticsearch:
    uris: localhost:9200
    username: elastic
    password: 222222
    connection-timeout: 1s
    socket-timeout: 15s
  ai:
    vectorstore:
      elasticsearch:
        initialize-schema: true
        dimensions: 1536
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen:1.8b
      embedding:
        model: nomic-embed-text:v1.5
  port: 22260
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  group-configs:
    - group: 'default'
      paths-to-match: '/**'